//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDesLivres.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErreurMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErreurMessage() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestionDesLivres.Domain.Resources.ErreurMessage", typeof(ErreurMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La date {0} doit être valide.
        /// </summary>
        internal static string DateValide {
            get {
                return ResourceManager.GetString("DateValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les données de l’enregistrement sont invalides ou incomplètes.
        /// </summary>
        internal static string DonneeInvalid {
            get {
                return ResourceManager.GetString("DonneeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un emprunt a déjà été effectué pour cette réservation.
        /// </summary>
        internal static string EmpruntEffectue {
            get {
                return ResourceManager.GetString("EmpruntEffectue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;entité {0} avec l&apos;ID {1} n&apos;a pas été trouvée..
        /// </summary>
        internal static string EnregistrementNonTrouve {
            get {
                return ResourceManager.GetString("EnregistrementNonTrouve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} avec &apos;{1}&apos; existe déjà..
        /// </summary>
        internal static string EntiteExisteDeja {
            get {
                return ResourceManager.GetString("EntiteExisteDeja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue lors de l&apos;ajout {0}..
        /// </summary>
        internal static string ErreurAjoutEntite {
            get {
                return ResourceManager.GetString("ErreurAjoutEntite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue lors de l&apos;exécution de l&apos;opération sur l&apos;entité {0}..
        /// </summary>
        internal static string ErreurGeneral {
            get {
                return ResourceManager.GetString("ErreurGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue lors de la modification {0}..
        /// </summary>
        internal static string ErreurModificationEntite {
            get {
                return ResourceManager.GetString("ErreurModificationEntite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de la recherche des {0}..
        /// </summary>
        internal static string ErreurRecherche {
            get {
                return ResourceManager.GetString("ErreurRecherche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue lors de la suppression {0}..
        /// </summary>
        internal static string ErreurSuppressionEntite {
            get {
                return ResourceManager.GetString("ErreurSuppressionEntite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de supprimer {0} lié(e) à des {1}.&quot;.
        /// </summary>
        internal static string ErreurSuppressionEntiteLiee {
            get {
                return ResourceManager.GetString("ErreurSuppressionEntiteLiee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La réservation est déjà annulée.
        /// </summary>
        internal static string ReservationAnnulee {
            get {
                return ResourceManager.GetString("ReservationAnnulee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette reservation a été déjà imprunté. Cette action ne peut se poursuivre.
        /// </summary>
        internal static string ReservationDejaEmpruntee {
            get {
                return ResourceManager.GetString("ReservationDejaEmpruntee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le livre n&apos;est pas disponible car le stock est épuisé.
        /// </summary>
        internal static string StockEpuise {
            get {
                return ResourceManager.GetString("StockEpuise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assurez-vous que toutes les données sont correctement fournies..
        /// </summary>
        internal static string ValeurNulle {
            get {
                return ResourceManager.GetString("ValeurNulle", resourceCulture);
            }
        }
    }
}
